name: test
description: A reusable Flutter architecture template.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.4
  get: ^4.7.3
  image_picker: ^1.2.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/images/app_icon.png
    - assets/images/amenities/
